[package]
name = "ecdh"
version = "0.0.12"
authors = ["Manuel Schölling <manuel.schoelling@gmx.de>"]
description = "For OpenSSL's ECDH"
homepage = "https://github.com/manuels/ecdh.rs"
license = " GPL-2.0"

[dependencies]
log = "0.3.1"
libc = "*"
