[package]

name = "ecdh"
version = "0.0.3"
authors = ["Manuel Schölling <manuel.schoelling@gmx.de>"]
description = "For OpenSSL's ECDH"
homepage = "https://github.com/manuels/ecdh.rs"
license = " GPL-2.0"
